language: python
env:
  matrix:
  - DEP_VERSIONS="oldest"
  - DEP_VERSIONS="latest"
  - DEP_VERSIONS="master"
python:
  - 2.7
  - 3.3
  - 3.4
before_install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
install:
  - sudo apt-get install phantomjs
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION pip coverage nose sphinx numpydoc flake8
  - source activate test-env
  - if [[ $DEP_VERSIONS == "oldest" ]]; then
      if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
        conda install numpy=1.9 scipy=0.14 sympy=0.7.4 cython=0.17 theano=0.7;
      else
        conda install numpy=1.9 scipy=0.14 sympy=0.7.5 cython=0.20 theano=0.7;
      fi
    elif [[ $DEP_VERSIONS == "latest" ]]; then
      conda install numpy scipy sympy cython theano;
    elif [[ $DEP_VERSIONS == "master" ]]; then
      conda install numpy scipy cython theano;
      pip install https://github.com/sympy/sympy/archive/master.zip;
    fi
before_script:
  - conda info
  - conda list
  - pip --version
  - pip freeze
script:
  # Run Python and Javascript tests.
  - nosetests -v --with-coverage --cover-package=pydy
  # JS tests
  - cd pydy/viz/static/js/tests && phantomjs run-jasmine.js SpecRunner.html
  - cd -  # It should not be combined with above command
  # Check Python and Javascript syntax (trailing whitespaces/newlines, unused imports).
  - (flake8 --select W1,W2,W3 --exclude booger . &&
    flake8 --select F401 --exclude booger,__init__.py,conf.py . &&
    flake8 --select W2,W3 --filename='*.js' examples/ pydy/viz/static/js/dyviz/) ||
    (echo "Please run a linter and fix errors, e.g. pylint, flake8, pep8, etc."; false)
  # Make sure the docs build.
  - cd docs && make html && cd ..
  # Make sure the library installs.
  - python setup.py install
  # Run benchmark
  - python bin/benchmark_pydy_code_gen.py 1 10
